import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { SessionProviderWrapper } from "@/components/providers/session-provider";
import { SWRProvider } from "@/components/providers/swr-provider";
import { SocketProvider } from "@/components/providers/socket-provider";
import "./globals.css";

const open = Open_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <SessionProviderWrapper>
      <SWRProvider>
        <SocketProvider>
          <html lang="en">
            <body className={open.className}>{children}</body>
          </html>
        </SocketProvider>
      </SWRProvider>
    </SessionProviderWrapper>
  );
}
